# Generated by Django 6.0 on 2026-07-01 07:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('specialization', models.CharField(choices=[('cultural', 'Cultural'), ('historical', 'Historical'), ('nature', 'Nature & Wildlife'), ('adventure', 'Adventure'), ('food', 'Food & Cuisine'), ('religious', 'Religious & Spiritual'), ('general', 'General')], default='general', max_length=20)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('languages', models.CharField(blank=True, help_text='Comma-separated list of languages spoken', max_length=200)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='guide_photos/')),
                ('average_rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guideprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('cultural', 'Cultural'), ('historical', 'Historical'), ('nature', 'Nature & Wildlife'), ('adventure', 'Adventure'), ('food', 'Food & Cuisine'), ('religious', 'Religious & Spiritual'), ('general', 'General')], default='general', max_length=20)),
                ('duration_hours', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(0.5)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('location', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='guides.guideprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
